In [46]:
import pandas as pd
import numpy as np
from herramientas import obtener_resumen_valores_unicos

In [47]:
df = pd.read_csv('data/train.csv')

In [48]:
df.head()

,id,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,...,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data,outcome
0,0,yes,adult,530001,38.1,132.0,24.0,cool,reduced,dark_cyanotic,...,57.0,8.5,serosanguious,3.4,yes,2209,0,0,no,died
1,1,yes,adult,533836,37.5,88.0,12.0,cool,normal,pale_cyanotic,...,33.0,64.0,serosanguious,2.0,yes,2208,0,0,no,euthanized
2,2,yes,adult,529812,38.3,120.0,28.0,cool,reduced,pale_pink,...,37.0,6.4,serosanguious,3.4,yes,5124,0,0,no,lived
3,3,yes,adult,5262541,37.1,72.0,30.0,cold,reduced,pale_pink,...,53.0,7.0,cloudy,3.9,yes,2208,0,0,yes,lived
4,4,no,adult,5299629,38.0,52.0,48.0,normal,normal,normal_pink,...,47.0,7.3,cloudy,2.6,no,0,0,0,yes,lived

In [49]:
obtener_resumen_valores_unicos(df)

,Columna,Tipo de Dato,Valores Únicos,Total Valores,Valores Nulos
0,id,int64,1235,1235,0
1,surgery,object,2,1235,0
2,age,object,2,1235,0
3,hospital_number,int64,255,1235,0
4,rectal_temp,float64,43,1235,0
5,pulse,float64,50,1235,0
6,respiratory_rate,float64,37,1235,0
7,temp_of_extremities,object,4,1196,39
8,peripheral_pulse,object,4,1175,60
9,mucous_membrane,object,6,1214,21
10,capillary_refill_time,object,3,1229,6
11,pain,object,6,1191,44
12,peristalsis,object,5,1215,20
13,abdominal_distention,object,4,1212,23
14,nasogastric_tube,object,3,1155,80
15,nasogastric_reflux,object,4,1214,21
16,nasogastric_reflux_ph,float64,26,1235,0
17,rectal_exam_feces,object,5,1045,190
18,abdomen,object,5,1022,213
19,packed_cell_volume,float64,49,1235,0
20,total_protein,float64,83,1235,0
21,abdomo_appearance,object,3,1187,48
22,abdomo_protein,float64,54,1235,0
23,surgical_lesion,object,2,1235,0
24,lesion_1,int64,57,1235,0
25,lesion_2,int64,4,1235,0
26,lesion_3,int64,2,1235,0
27,cp_data,object,2,1235,0
28,outcome,object,3,1235,0

In [50]:
# Eliminar filas con valores nulos
df = df.dropna()

In [51]:
df = df.drop('id', axis=1)

In [52]:
obtener_resumen_valores_unicos(df)

,Columna,Tipo de Dato,Valores Únicos,Total Valores,Valores Nulos
0,surgery,object,2,771,0
1,age,object,2,771,0
2,hospital_number,int64,213,771,0
3,rectal_temp,float64,39,771,0
4,pulse,float64,49,771,0
5,respiratory_rate,float64,34,771,0
6,temp_of_extremities,object,4,771,0
7,peripheral_pulse,object,4,771,0
8,mucous_membrane,object,6,771,0
9,capillary_refill_time,object,3,771,0
10,pain,object,5,771,0
11,peristalsis,object,4,771,0
12,abdominal_distention,object,4,771,0
13,nasogastric_tube,object,3,771,0
14,nasogastric_reflux,object,4,771,0
15,nasogastric_reflux_ph,float64,23,771,0
16,rectal_exam_feces,object,5,771,0
17,abdomen,object,5,771,0
18,packed_cell_volume,float64,48,771,0
19,total_protein,float64,80,771,0
20,abdomo_appearance,object,3,771,0
21,abdomo_protein,float64,51,771,0
22,surgical_lesion,object,2,771,0
23,lesion_1,int64,51,771,0
24,lesion_2,int64,3,771,0
25,lesion_3,int64,2,771,0
26,cp_data,object,2,771,0
27,outcome,object,3,771,0

In [53]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df['outcome'] = label_encoder.fit_transform(df['outcome'])

In [54]:
# Lista de nombres de las variables categóricas que deseas codificar
variables_categoricas = ['surgery', 'age', 'temp_of_extremities', 'peripheral_pulse', 'mucous_membrane', 'capillary_refill_time', 'pain', 'peristalsis', 'abdominal_distention', 'nasogastric_tube', 'nasogastric_reflux', 'rectal_exam_feces', 'abdomen', 'abdomo_appearance', 'surgical_lesion', 'cp_data']

# Aplicar one-hot encoding a todas las variables categóricas en la lista
df_encoded = pd.get_dummies(df, columns=variables_categoricas, drop_first=True)

In [58]:
from sklearn.model_selection import train_test_split

X = df_encoded.drop('outcome', axis=1)
y = df_encoded['outcome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=15)

# modelo Random Forest Classifier

In [59]:
# Importa el modelo Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier

# Crea una instancia del modelo
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Paso 5: Entrenamiento del modelo
model.fit(X_train, y_train)

# Paso 6: Evaluación del modelo
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(classification_rep)

# Paso 7: Ajuste final del modelo (si es necesario)

# Paso 8: Predicciones en nuevos datos
# Puedes usar model.predict() para hacer predicciones en nuevos datos

Accuracy: 0.7032258064516129
Confusion Matrix:
[[49  1 21]
 [ 5  7  7]
 [10  2 53]]
Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.69      0.73        71
           1       0.70      0.37      0.48        19
           2       0.65      0.82      0.73        65

    accuracy                           0.70       155
   macro avg       0.71      0.62      0.64       155
weighted avg       0.71      0.70      0.70       155