In [1]:
import pandas as pd
import numpy as np
from herramientas import obtener_resumen_valores_unicos

In [2]:
df_train = pd.read_csv('data/train.csv')
df_test = pd.read_csv('data/test.csv')

In [3]:
data_to_add = {
    'outcome': [8] * len(df_test),

}

# Convierte el diccionario en un nuevo DataFrame
new_columns_df = pd.DataFrame(data_to_add)

# Concatena el DataFrame original ('df') con el nuevo DataFrame
df_test = pd.concat([df_test, new_columns_df], axis=1)

In [4]:
df= pd.concat([df_test, df_train], axis=0)

In [5]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [6]:
df.head()

,id,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,pain,peristalsis,abdominal_distention,nasogastric_tube,nasogastric_reflux,nasogastric_reflux_ph,rectal_exam_feces,abdomen,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data,outcome
0,1235,no,adult,534053,38.6,40.0,20.0,normal,normal,normal_pink,less_3_sec,mild_pain,hypomotile,slight,none,none,7.0,normal,distend_small,42.0,7.5,clear,2.3,no,0,0,0,no,8
1,1236,yes,adult,528469,38.2,112.0,48.0,cool,reduced,bright_pink,more_3_sec,depressed,hypomotile,moderate,slight,none,3.5,decreased,distend_small,44.0,6.0,serosanguious,2.6,no,2208,0,0,yes,8
2,1237,yes,adult,528178,37.7,66.0,12.0,cool,normal,bright_red,less_3_sec,mild_pain,hypomotile,slight,slight,none,3.0,normal,distend_small,31.5,6.0,cloudy,1.6,yes,2205,0,0,yes,8
3,1238,no,adult,534784,37.1,88.0,20.0,cool,reduced,pale_cyanotic,less_3_sec,depressed,absent,severe,slight,more_1_liter,2.0,absent,distend_large,75.0,81.0,NaN,1.0,yes,1400,0,0,no,8
4,1239,yes,adult,529840,38.3,50.0,12.0,NaN,normal,bright_pink,less_3_sec,mild_pain,absent,slight,slight,none,3.0,decreased,distend_small,37.0,6.8,cloudy,2.6,yes,2208,0,0,yes,8

In [7]:
obtener_resumen_valores_unicos(df)

,Columna,Tipo de Dato,Valores Únicos,Total Valores,Valores Nulos
0,id,int64,2059,2059,0
1,surgery,object,2,2059,0
2,age,object,2,2059,0
3,hospital_number,int64,271,2059,0
4,rectal_temp,float64,43,2059,0
5,pulse,float64,51,2059,0
6,respiratory_rate,float64,42,2059,0
7,temp_of_extremities,object,4,1985,74
8,peripheral_pulse,object,4,1952,107
9,mucous_membrane,object,6,2025,34
10,capillary_refill_time,object,3,2047,12
11,pain,object,7,1986,73
12,peristalsis,object,5,2020,39
13,abdominal_distention,object,4,2014,45
14,nasogastric_tube,object,3,1915,144
15,nasogastric_reflux,object,4,2024,35
16,nasogastric_reflux_ph,float64,30,2059,0
17,rectal_exam_feces,object,5,1744,315
18,abdomen,object,5,1692,367
19,packed_cell_volume,float64,51,2059,0
20,total_protein,float64,85,2059,0
21,abdomo_appearance,object,3,1980,79
22,abdomo_protein,float64,60,2059,0
23,surgical_lesion,object,2,2059,0
24,lesion_1,int64,61,2059,0
25,lesion_2,int64,5,2059,0
26,lesion_3,int64,2,2059,0
27,cp_data,object,2,2059,0
28,outcome,object,4,2059,0

In [8]:
# Obtén una lista de las columnas categóricas (tipos object)
columnas_categoricas = df.select_dtypes(include=['object']).columns

# Itera a través de las columnas categóricas y muestra los valores únicos
for columna in columnas_categoricas:
    valores_unicos = df[columna].unique()
    print(f'Valores únicos en la columna "{columna}":')
    for valor in valores_unicos:
        print(valor)
    print('\n')

Valores únicos en la columna "surgery":
no
yes


Valores únicos en la columna "age":
adult
young


Valores únicos en la columna "temp_of_extremities":
normal
cool
nan
cold
warm


Valores únicos en la columna "peripheral_pulse":
normal
reduced
nan
absent
increased


Valores únicos en la columna "mucous_membrane":
normal_pink
bright_pink
bright_red
pale_cyanotic
dark_cyanotic
pale_pink
nan


Valores únicos en la columna "capillary_refill_time":
less_3_sec
more_3_sec
nan
3


Valores únicos en la columna "pain":
mild_pain
depressed
severe_pain
extreme_pain
nan
moderate
alert
slight


Valores únicos en la columna "peristalsis":
hypomotile
absent
hypermotile
nan
normal
distend_small


Valores únicos en la columna "abdominal_distention":
slight
moderate
severe
none
nan


Valores únicos en la columna "nasogastric_tube":
none
slight
nan
significant


Valores únicos en la columna "nasogastric_reflux":
none
more_1_liter
less_1_liter
nan
slight


Valores únicos en la columna "rectal_exam_feces":
normal
decreased
absent
nan
increased
serosanguious


Valores únicos en la columna "abdomen":
distend_small
distend_large
nan
other
firm
normal


Valores únicos en la columna "abdomo_appearance":
clear
serosanguious
cloudy
nan


Valores únicos en la columna "surgical_lesion":
no
yes


Valores únicos en la columna "cp_data":
no
yes


Valores únicos en la columna "outcome":
8
died
euthanized
lived

In [6]:
import pandas as pd

# Agrupar por la columna 'temp_of_extremities' y calcular las estadísticas
grouped = df_test.groupby('temp_of_extremities')['rectal_temp']

# Calcular los valores deseados
min_temp = grouped.min()
max_temp = grouped.max()
mean_temp = grouped.mean()
median_temp = grouped.median()

# Mostrar los resultados
result_df = pd.DataFrame({
    'Mínimo': min_temp,
    'Máximo': max_temp,
    'Media': mean_temp,
    'Mediana': median_temp
})

print(result_df)

                     Mínimo  Máximo      Media  Mediana
temp_of_extremities
cold                   37.0    40.8  38.459302     38.4
cool                   36.0    40.8  38.260593     38.2
normal                 37.0    39.5  38.132323     38.1
warm                   36.0    40.3  38.109091     38.1

In [7]:
# Agrupar por la columna 'temp_of_extremities' y calcular las estadísticas
grouped = df_train.groupby('temp_of_extremities')['rectal_temp']

# Calcular los valores deseados
min_temp = grouped.min()
max_temp = grouped.max()
mean_temp = grouped.mean()
median_temp = grouped.median()

# Mostrar los resultados
result_df = pd.DataFrame({
    'Mínimo': min_temp,
    'Máximo': max_temp,
    'Media': mean_temp,
    'Mediana': median_temp
})

print(result_df)

                     Mínimo  Máximo      Media  Mediana
temp_of_extremities
cold                   36.0    40.3  38.311570     38.3
cool                   35.4    40.8  38.214429     38.1
normal                 36.5    40.3  38.135494     38.1
warm                   37.0    39.4  38.254902     38.3

In [8]:
# Utiliza el método replace para hacer el reemplazo
df_train['temp_of_extremities'] = df_train['temp_of_extremities'].replace('cold', 'cool')
df_test['temp_of_extremities'] = df_test['temp_of_extremities'].replace('cold', 'cool')

In [9]:
# Agrupar por la columna 'temp_of_extremities' y calcular las estadísticas
grouped = df_test.groupby('temp_of_extremities')['rectal_temp']

# Calcular los valores deseados
min_temp = grouped.min()
max_temp = grouped.max()
mean_temp = grouped.mean()
median_temp = grouped.median()

# Mostrar los resultados
result_df = pd.DataFrame({
    'Mínimo': min_temp,
    'Máximo': max_temp,
    'Media': mean_temp,
    'Mediana': median_temp
})

print(result_df)

                     Mínimo  Máximo      Media  Mediana
temp_of_extremities
cool                   36.0    40.8  38.291219     38.2
normal                 37.0    39.5  38.132323     38.1
warm                   36.0    40.3  38.109091     38.1